# erlang.mk Makefile for tinymt-erlang

PROJECT = sshrpc

#CT_SUITES = tinymt32
ERLC_OPTS = +debug_info +warn_export_all +warn_export_vars \
	        +warn_shadow_vars +warn_obsolete_guard +bin_opt_info +warn_missing_spec
# Uncomment this for enabling HiPE
#ERLC_OPTS += +native "+{hipe, [o3]}"

include erlang.mk
